name: flutter_onscreen_keyboard
description: >
  A customizable and extensible virtual keyboard widget
  for Flutter desktop and touchscreen apps.

version: 0.1.1

resolution: workspace

homepage: https://github.com/albinpk/flutter_onscreen_keyboard
repository: https://github.com/albinpk/flutter_onscreen_keyboard
issue_tracker: https://github.com/albinpk/flutter_onscreen_keyboard/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

topics:
  - keyboard
  - virtual-keyboard
  - onscreen-keyboard
  - flutter-keyboard
  - flutter-onscreen-keyboard
